MODEL_NAME: "FastSurferVINN"
NUM_CLASSES: 51
LOSS_FUNC: "combined"
NUM_FILTERS: 71
NUM_FILTERS_INTERPOL: 32
NUM_CHANNELS: 7
KERNEL_H: 3
KERNEL_W: 3
KERNEL_C: 1
STRIDE_CONV: 1
STRIDE_POOL: 2
POOL: 2
HEIGHT: 256
WIDTH: 256
BASE_RES: 1.0
INTERPOLATION_MODE: "bilinear"
CROP_POSITION: "top_left"
OUT_TENSOR_WIDTH: 320
OUT_TENSOR_HEIGHT: 320